[package]
name = "guess_my_number"
version = "0.1.0"
authors = ["Chetan Mistry <cmistry98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
text_io = "0.1.7"
clap = "2.33.0"
